# Docker image configuration
image:
  file: .gitpod.Dockerfile

# Commands to run on workspace startup
tasks:
  - init: echo 'Initial setup commands here'
    command: echo 'Startup commands here'

# Ports to expose
ports:
  - port: 3000
    onOpen: open-preview