version: '1'

ignore:
  - .git
  - .github
  - venv
  - env
  - .env
  - node_modules
  - build
  - dist

rule_settings:
  enable:
    - default
    - python-best-practices
  python_version: '3.11'

metrics:
  quality_threshold: 80.0

clone_detection:
  min_lines: 3
  min_duplicates: 2
  identical_clones_only: false 