-- Create tablespace for RDF storage
CREATE TABLESPACE ONTOLOGY_FRAMEWORK
DATAFILE SIZE 1024M AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
SEGMENT SPACE MANAGEMENT AUTO;

-- Create dedicated user for RDF operations using IAM authentication
CREATE USER RDF_USER IDENTIFIED EXTERNALLY
DEFAULT TABLESPACE ONTOLOGY_FRAMEWORK;

-- Grant necessary privileges
GRANT CONNECT, RESOURCE TO RDF_USER;
GRANT CREATE VIEW TO RDF_USER;
GRANT UNLIMITED TABLESPACE ON ONTOLOGY_FRAMEWORK TO RDF_USER;
GRANT EXECUTE ON MDSYS.SEM_APIS TO RDF_USER;
GRANT EXECUTE ON MDSYS.SEM_APIS_INTERNAL TO RDF_USER;
GRANT SELECT ON MDSYS.RDF_PARAMETER_TABLE TO RDF_USER;
GRANT SELECT ANY TABLE TO RDF_USER;
GRANT CREATE ANY TABLE TO RDF_USER;

-- Exit
EXIT; 