version: '3.8'

services:
  fuseki:
    image: stain/jena-fuseki:latest
    environment:
      - ADMIN_PASSWORD=admin
      - JVM_ARGS=-Xmx2g
    ports:
      - "3030:3030"
    volumes:
      - fuseki-data:/fuseki
      - fuseki-config:/config

volumes:
  fuseki-data:
  fuseki-config: 