name: ontology-framework-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytest
  - pytest-cov
  - black
  - mypy
  - rdflib
  - pyshacl
  - networkx
  - pandas
  - numpy
  - jupyter
  - ipykernel
  - pip:
    - -e .
    - pre-commit
    - pytest-asyncio
    - pytest-mock
    - pytest-xdist
    - coverage
    - sphinx
    - sphinx-rtd-theme
    - sphinx-autodoc-typehints
    - safety
    - bandit
    - pylint
    - flake8
    - isort
    - blacken-docs
    - doc8
    - recommonmark
    - myst-parser
    - sphinx-copybutton
    - sphinx-autobuild
    - sphinx-autodoc-typehints
    - sphinx-rtd-theme
    - sphinx-tabs
    - sphinx-toolbox
    - sphinxcontrib-bibtex
    - sphinxcontrib-mermaid
    - sphinxcontrib-plantuml
    - sphinxcontrib-programoutput
    - sphinxcontrib-spelling
    - sphinxcontrib-svg2pdfconverter
    - sphinxcontrib-websupport
    - sphinxcontrib-youtube
    - sphinx-panels
    - sphinx-prompt
    - sphinx-rtd-dark-mode
    - sphinx-rtd-size
    - sphinx-rtd-theme
    - sphinx-tabs
    - sphinx-toolbox
    - sphinxcontrib-bibtex
    - sphinxcontrib-mermaid
    - sphinxcontrib-plantuml
    - sphinxcontrib-programoutput
    - sphinxcontrib-spelling
    - sphinxcontrib-svg2pdfconverter
    - sphinxcontrib-websupport
    - sphinxcontrib-youtube
    - sphinx-panels
    - sphinx-prompt
    - sphinx-rtd-dark-mode
    - sphinx-rtd-size 