channels:
- conda-forge
- defaults
dependencies:
- python=3.10
- pip
- rdflib>=6.0.0
- click>=8.0.0
- jinja2>=3.0.0
- black>=22.0.0
- pytest>=7.0.0
- pytest-cov>=4.0.0
- pytest-asyncio>=0.21.0
- rich>=10.0.0
- requests>=2.0.0
- python-dotenv>=0.19.0
- pyyaml>=6.0.0
- PyGithub>=2.1.0
- pyshacl>=0.20.0
- networkx>=3.0
- matplotlib>=3.7
- pandas>=2.0
- mypy>=1.0
- pylint>=2.17
- streamlit>=1.32
- spacy>=3.7.0
- faiss-cpu>=1.7.0
- semver>=3.0.0
- pip:
  - oracledb>=1.3.0
  - isort>=5.12.0
  - pytest-docker>=1.0.0
  - -e .
  - graphviz>=0.20
  - pygraphviz>=1.11
  - streamlit-agraph>=0.0.5
  - streamlit-option-menu>=0.3.6
  - streamlit-extras>=0.2.6
  - streamlit-folium>=0.11.0
  - streamlit-vega-lite>=0.1.0
  - PyPDF2>=3.0.0
  - httpx>=0.24.0
  - yt-dlp>=2023.0
  - fastmcp
name: ontology-framework
