name: ontology-framework
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*
  - pip
  - rdflib>=6.0.0
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - black>=22.0.0
  - pip:
    - oracledb>=1.0.0
    - isort>=5.0.0
    - mypy>=1.0.0
