name: ontology-framework
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - bzip2
  - ca-certificates
  - libexpat
  - libffi
  - libsqlite
  - libzlib
  - ncurses
  - openssl
  - readline
  - setuptools
  - tk
  - tzdata
  - wheel
  - xz
