#!/bin/bash
git add \
    agent_declaration.ttl \
    bfg9k_alignment_report.ttl \
    bfg9k_diagnostic_broadcast.ttl \
    bfg9k_diagnostic_response.ttl \
    bfg9k_implementation_response.ttl \
    bfg9k_stdio_alignment_report.ttl \
    bfg9k_stdio_broadcast_response.ttl \
    build_app.sh \
    cdp_test.py \
    cdp_test_selenium.py \
    chroma_acknowledgment.ttl \
    chrome/ \
    chrome_devtools_bridge.py \
    chromedriver/ \
    claude_conversation.json \
    claude_grep.py \
    cookies.json \
    create_spore_zip.py \
    elmo_relay.ttl \
    entitlements.plist \
    error_screenshot.png \
    example_environment.yml \
    example_pyproject.toml \
    guidance/modules/validation/ \
    inspect_ui.applescript \
    inspect_ui.scpt \
    mac_ui_inspector.py \
    notebooks/ \
    ontology-anthology/ \
    ontology-framework-files.txt \
    project_snapshot.ttl \
    selenium_bridge.py \
    selenuim_chat.py \
    session.ttl.backup \
    spore_BroadcastResponse019.ttl \
    spore_integration_message.md \
    spore_response.ttl \
    spores/ \
    src/ontology_framework/extensions/ \
    src/ontology_framework/performance_monitor.py \
    start_chrome_debug.sh \
    test_integration/ \
    test_session.ttl \
    tests/extensions/ \
    tests/test_performance_monitor.py \
    timeout_screenshot.png \
    ui_automation_findings.ttl \
    validation_enhancement_proposal.ttl \
    validation_enhancements.ttl
