-- Connect as SYSDBA to grant privileges
CONNECT / AS SYSDBA;

-- Grant execute on SEM_APIS to admin
GRANT EXECUTE ON MDSYS.SEM_APIS TO admin;

-- Grant additional semantic privileges
GRANT EXECUTE ON MDSYS.SDO_SEM_INFERENCE TO admin;
GRANT EXECUTE ON MDSYS.SDO_SEM_UPDATE_CTX TO admin;
GRANT EXECUTE ON MDSYS.SDO_SEM_VALIDATE TO admin;
GRANT EXECUTE ON MDSYS.SDO_SEM_PERF TO admin;

-- Grant access to semantic network
GRANT SELECT ON MDSYS.SEM_MODEL$ TO admin;
GRANT SELECT ON MDSYS.SEM_DTYPE_INDEX_INFO TO admin;
GRANT SELECT ON MDSYS.SEM_NETWORK_INDEX_INFO TO admin;

-- Exit
EXIT; 