-- Grant RDF privileges
GRANT EXECUTE ON MDSYS.SEM_APIS TO ADMIN;
GRANT EXECUTE ON MDSYS.SEM_MATCH TO ADMIN;
GRANT EXECUTE ON MDSYS.SEM_MODELS TO ADMIN;
GRANT EXECUTE ON MDSYS.SDO_RDF_TRIPLE_S TO ADMIN;
GRANT SELECT ON MDSYS.RDF_VALUE$ TO ADMIN;
GRANT SELECT ON MDSYS.RDF_MODEL$ TO ADMIN;
GRANT SELECT ON MDSYS.RDF_PARAMETER TO ADMIN;
GRANT SELECT ON MDSYS.RDF_LINK$ TO ADMIN;
GRANT SELECT ON MDSYS.RDF_NAMESPACE$ TO ADMIN;
GRANT SELECT ON MDSYS.RDF_TERM_STATS$ TO ADMIN;
GRANT SELECT ON MDSYS.RDF_PRED_STATS$ TO ADMIN;
GRANT SELECT ON MDSYS.RDF_RULE$ TO ADMIN;
GRANT SELECT ON MDSYS.RDF_RULEBASE$ TO ADMIN;
GRANT SELECT ON MDSYS.RDF_NETWORK_INDEX_INTERNAL$ TO ADMIN;
GRANT SELECT ON MDSYS.RDF_MODEL_INTERNAL$ TO ADMIN;
GRANT SELECT ON MDSYS.RDF_GRANT_INFO$ TO ADMIN;
GRANT SELECT ON MDSYS.RDF_HIST$ TO ADMIN;
GRANT SELECT ON MDSYS.RDF_DELTA$ TO ADMIN;
GRANT SELECT ON MDSYS.RDF_COLLISION$ TO ADMIN;
GRANT SELECT ON MDSYS.RDF_CLIQUE$ TO ADMIN;
GRANT SELECT ON MDSYS.RDF_CRS_URI$ TO ADMIN;
GRANT SELECT ON MDSYS.RDF_DTYPE_INDEX_INFO_TBL TO ADMIN;
GRANT SELECT ON MDSYS.RDF_PARAM$_TBL TO ADMIN;
GRANT SELECT ON MDSYS.RDF_MODEL$_TBL TO ADMIN;
GRANT SELECT ON MDSYS.RDF_PRECOMP$ TO ADMIN;
GRANT SELECT ON MDSYS.RDF_PRECOMP_DEP$ TO ADMIN;
GRANT SELECT ON MDSYS.RDF_SESSION_EVENT$ TO ADMIN;
GRANT SELECT ON MDSYS.RDF_SYSTEM_EVENT$ TO ADMIN;
GRANT SELECT ON MDSYS.RDF_SPM$ TO ADMIN;
GRANT SELECT ON MDSYS.RDF_TS$ TO ADMIN;

-- Grant RDF roles
GRANT RDF_APIS_INTERNAL_ROLE TO ADMIN;
GRANT RDF_APIS_USER_ROLE TO ADMIN; 