apiVersion: apps/v1
kind: Deployment
metadata:
  name: ontology-framework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ontology-framework
  template:
    metadata:
      labels:
        app: ontology-framework
    spec:
      containers:
      - name: ontology-framework
        image: docker.io/louspringer/ontology-framework-dev:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ontology-framework-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: ontology-framework