[build-system]
requires = ["setuptools>=64.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ontology-framework"
version = "0.1"
description = "Ontology Framework with Directory Sync Utility"
requires-python = ">=3.11"
authors = [
    {name = "Lou Springer", email = "your.email@example.com"}
]
license = {text = "MIT"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11",
]

[project.scripts]
sync-cli = "directory_sync.cli:main"

[tool.setuptools]
packages = ["directory_sync"] 