-- Simple connection test
SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') AS USERNAME,
       SYS_CONTEXT('USERENV', 'CON_NAME') AS CONTAINER,
       SYS_CONTEXT('USERENV', 'DB_NAME') AS DB_NAME
FROM DUAL;

exit; 