-- Test connection using environment variables
SET ECHO ON
SET FEEDBACK ON
DEFINE ORACLE_USER
DEFINE ORACLE_PASSWORD
DEFINE ORACLE_DSN

-- Connect using environment variables
CONNECT &ORACLE_USER/&ORACLE_PASSWORD@&ORACLE_DSN

-- Verify connection
SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') AS USERNAME,
       SYS_CONTEXT('USERENV', 'CON_NAME') AS CONTAINER,
       SYS_CONTEXT('USERENV', 'DB_NAME') AS DB_NAME
FROM DUAL;

exit; 