version: '3.8'
services:
  promptdb:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: prompts
      POSTGRES_USER: promptuser
      POSTGRES_PASSWORD: promptpass
    volumes:
      - prompt_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  prompt_data: 