"""
Common types and enums for the ontology framework.
"""

from typing import Dict, List, Optional, Union, Any
from datetime import datetime
from enum import Enum, auto

class PatchType(Enum):
    """Types of patches that can be applied."""
    MINOR = "minor"
    MAJOR = "major"
    CRITICAL = "critical"
    SECURITY = "security"
    DEPENDENCY = "dependency"
    DOCUMENTATION = "documentation"
    TEST = "test"
    REFACTOR = "refactor"
    PERFORMANCE = "performance"
    FEATURE = "feature"
    BUGFIX = "bugfix"
    ENHANCEMENT = "enhancement"
    MAINTENANCE = "maintenance"
    COMPLIANCE = "compliance"
    SECURITY_PATCH = "security_patch"
    DEPENDENCY_UPDATE = "dependency_update"
    DOCUMENTATION_UPDATE = "documentation_update"
    TEST_UPDATE = "test_update"
    REFACTORING = "refactoring"
    PERFORMANCE_OPTIMIZATION = "performance_optimization"
    FEATURE_ADDITION = "feature_addition"
    BUG_FIX = "bug_fix"
    ENHANCEMENT_UPDATE = "enhancement_update"
    MAINTENANCE_UPDATE = "maintenance_update"
    COMPLIANCE_UPDATE = "compliance_update"

class PatchStatus(Enum):
    """Status of a patch."""
    DRAFT = "draft"
    REVIEW = "review"
    APPROVED = "approved"
    REJECTED = "rejected"
    MERGED = "merged"
    DEPLOYED = "deployed"
    ROLLED_BACK = "rolled_back"
    FAILED = "failed"
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    CANCELLED = "cancelled"
    BLOCKED = "blocked"
    UNBLOCKED = "unblocked"
    SCHEDULED = "scheduled"
    UNSCHEDULED = "unscheduled"
    PRIORITIZED = "prioritized"
    DEPRIORITIZED = "deprioritized"
    ARCHIVED = "archived"
    RESTORED = "restored"

class ErrorSeverity(Enum):
    """Severity levels for errors."""
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"
    FATAL = "fatal"
    DEBUG = "debug"
    TRACE = "trace"
    NOTICE = "notice"
    ALERT = "alert"
    EMERGENCY = "emergency"

class ErrorType(Enum):
    """Types of errors that can occur."""
    VALIDATION = "validation"
    RUNTIME = "runtime"
    CONFIGURATION = "configuration"
    NETWORK = "network"
    DATABASE = "database"
    FILE_SYSTEM = "file_system"
    MEMORY = "memory"
    CPU = "cpu"
    DISK = "disk"
    API = "api"
    AUTHENTICATION = "authentication"
    AUTHORIZATION = "authorization"
    COMPLIANCE = "compliance"
    SECURITY = "security"
    PERFORMANCE = "performance"
    SCALABILITY = "scalability"
    AVAILABILITY = "availability"
    RELIABILITY = "reliability"
    MAINTAINABILITY = "maintainability"
    DATA_LOSS = "data_loss"
    IO = "io"
    TEST = "test"

class ValidationRule(Enum):
    """Types of validation rules."""
    SENSITIVE_DATA = "Sensitive Data"
    RISK = "Risk"
    MATRIX = "Matrix"
    COMPLIANCE = "Compliance"
    SECURITY = "Security"
    PERFORMANCE = "Performance"
    RELIABILITY = "Reliability"
    AVAILABILITY = "Availability"
    SCALABILITY = "Scalability"
    MAINTAINABILITY = "Maintainability"
    SEVERITY = "Error Severity"
    STEP_ORDER = "Step Order"

class ErrorStep(Enum):
    """Steps in the error handling process."""
    IDENTIFICATION = "identification"
    ANALYSIS = "analysis"
    RECOVERY = "recovery"
    PREVENTION = "prevention"
    SETUP = "setup"
    EXECUTION = "execution"
    VALIDATION = "validation"
    CLEANUP = "cleanup"
    MONITORING = "monitoring"
    REPORTING = "reporting"
    DOCUMENTATION = "documentation"
    REVIEW = "review"
    APPROVAL = "approval"
    IMPLEMENTATION = "implementation"
    TESTING = "testing"
    DEPLOYMENT = "deployment"
    VERIFICATION = "verification"
    CLOSURE = "closure"

class RiskLevel(Enum):
    """Levels of risk."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"
    UNKNOWN = "unknown"
    NONE = "none"
    MINIMAL = "minimal"
    MODERATE = "moderate"
    SEVERE = "severe"
    EXTREME = "extreme"

class ComplianceLevel(Enum):
    """Levels of compliance."""
    NOT_STARTED = "not_started"
    IN_PROGRESS = "in_progress"
    PARTIAL = "partial"
    FULL = "full"
    VERIFIED = "verified"
    CERTIFIED = "certified"
    UNKNOWN = "unknown"
    NON_COMPLIANT = "non_compliant"
    COMPLIANT = "compliant"
    EXEMPT = "exempt"
    WAIVED = "waived"
    PENDING = "pending"
    REVIEW = "review"
    APPROVED = "approved"
    REJECTED = "rejected"

class SecurityLevel(Enum):
    """Levels of security."""
    PUBLIC = "public"
    INTERNAL = "internal"
    CONFIDENTIAL = "confidential"
    SECRET = "secret"
    TOP_SECRET = "top_secret"
    RESTRICTED = "restricted"
    SENSITIVE = "sensitive"
    PRIVATE = "private"
    PROTECTED = "protected"
    CLASSIFIED = "classified"
    UNCLASSIFIED = "unclassified"
    MEDIUM = "medium"
    HIGH = "high"
    LOW = "low"

class PerformanceMetric(Enum):
    """Types of performance metrics."""
    RESPONSE_TIME = "response_time"
    THROUGHPUT = "throughput"
    LATENCY = "latency"
    BANDWIDTH = "bandwidth"
    CPU_USAGE = "cpu_usage"
    MEMORY_USAGE = "memory_usage"
    DISK_USAGE = "disk_usage"
    NETWORK_USAGE = "network_usage"
    ERROR_RATE = "error_rate"
    SUCCESS_RATE = "success_rate"
    AVAILABILITY = "availability"
    RELIABILITY = "reliability"
    SCALABILITY = "scalability"
    MAINTAINABILITY = "maintainability"
    SECURITY = "security"
    COMPLIANCE = "compliance"
    COST = "cost"
    EFFICIENCY = "efficiency"
    EFFECTIVENESS = "effectiveness"
    QUALITY = "quality"
    SATISFACTION = "satisfaction"
    USABILITY = "usability"
    ACCESSIBILITY = "accessibility"
    INTEROPERABILITY = "interoperability"
    PORTABILITY = "portability"
    REUSABILITY = "reusability"
    TESTABILITY = "testability"
    UNDERSTANDABILITY = "understandability"
    MODIFIABILITY = "modifiability"
    ANALYZABILITY = "analyzability"
    STABILITY = "stability"
    CHANGEABILITY = "changeability" 