name: Build and Push Dev Container

on:
  # Temporary trigger to force registration
  push:
    branches:
      - '**'  # Match all branches including those with slashes
  workflow_dispatch:  # Allow manual triggers
  pull_request:
    paths:
      - '.devcontainer/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push dev container
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .devcontainer/Dockerfile
          push: true
          tags: |
            louspringer/ontology-framework-dev:latest
            louspringer/ontology-framework-dev:${{ github.sha }}