name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    services:
      graphdb:
        image: ontotext/graphdb:10.3.0
        ports:
          - 7200:7200
        env:
          GDB_HEAP_SIZE: 2g
        options: >-
          --health-cmd "curl -f http://localhost:7200/rest/repositories || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
        
    - name: Wait for GraphDB
      run: |
        until curl -s http://localhost:7200/rest/repositories > /dev/null; do
          echo "Waiting for GraphDB..."
          sleep 5
        done
        
    - name: Run namespace validation
      run: |
        python scripts/namespace_dependency_analyzer.py
        python scripts/analyze_usage_patterns.py
        
    - name: Run tests
      run: |
        pytest tests/ --cov=src --cov-report=xml
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true 