name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,defaults
        activate-environment: ontology-framework
        environment-file: environment.yml
        auto-activate-base: false
        
    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest tests/ --cov=src --cov-report=xml
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        
    - name: Run patch validation
      shell: bash -l {0}
      run: |
        python -m ontology_framework.modules.patch_management validate-all
        
    - name: Check Docker build
      run: |
        docker build -t ontology-framework:test .
        docker images ontology-framework:test --format "{{.Size}}"
        
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.10'
        channels: conda-forge,defaults
        activate-environment: ontology-framework
        environment-file: environment.yml
        auto-activate-base: false
        
    - name: Run linters
      shell: bash -l {0}
      run: |
        black --check .
        flake8 .
        mypy src/
        
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.10'
        channels: conda-forge,defaults
        activate-environment: ontology-framework
        environment-file: environment.yml
        auto-activate-base: false
        
    - name: Run security checks
      shell: bash -l {0}
      run: |
        safety check
        bandit -r src/
        
  docker:
    runs-on: ubuntu-latest
    needs: [test, lint, security]
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: ontology-framework:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Measure image size
      run: |
        docker images ontology-framework:latest --format "{{.Size}}"
        
  performance:
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.10'
        channels: conda-forge,defaults
        activate-environment: ontology-framework
        environment-file: environment.yml
        auto-activate-base: false
        
    - name: Run performance tests
      shell: bash -l {0}
      run: |
        python -m ontology_framework.tests.performance
        
    - name: Upload performance report
      uses: actions/upload-artifact@v3
      with:
        name: performance-report
        path: performance-report.json 